shared:
  image: node:20

subscribe:
    scmUrls:
        - https://github.com/VonnyJap/test-subscribe-parent.git: ['~commit']
jobs:
  random:
    template: sd/noop@latest
    requires: [~pr, ~commit, ~subscribe]
