shared:
  image: node:20

subscribe:
    scmUrls:
        - https://github.com/VonnyJap/test-pr-config-second.git: ['~commit', '~pr']
jobs:
  random:
    template: sd/noop@latest
    requires: [~pr, ~commit, ~subscribe]
