shared:
  image: node:20
annotations:
  screwdriver.cd/chainPR: true
jobs:
  second:
    template: sd/noop@latest
    requires: [~pr, ~commit]
    steps:
    - noop: |
        echo "true"
    - teardown-step: |
        echo $(meta get meta.build_status)
        meta set meta.status.first '{"status":"SUCCESS","message":"Coverage is above 80%."}'
  first:
    template: sd/noop@latest
    requires: [second]
